parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'
    exports_directory: '%kernel.project_dir%/var/exports'
    url_api_list_destinations: 'http://localhost:8000/api/destinations'